---
title: "My Report as a Vingette"
output:
    bookdown::html_document2:
      base_format: rmarkdown::html_vignette
      number_sections: false
vignette: >
  %\VignetteIndexEntry{my-report-as-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.width = 5,
  fig.retina = 2,
  comment = "#>"
)
```

```{r setup}
library(mysimplecompendium)
```

```{r starwars-gender-plot, fig.cap="Gender of Starwars characters"}
library(tidyverse)
library(here)

starwars %>% 
  mutate(gender_fct = fct_infreq(gender)) %>% 
  ggplot(aes(gender_fct)) +
  geom_bar() +
  xlab("") +
  theme_minimal(base_size = 14)
```

In Figure \@ref(fig:starwars-gender-plot) we can see that there is an imbalance in the gender ratios of Starwars characters. This needs to be fixed. 

# Other files in /vignettes

We can put anything in `/vingettes`, such as data files:

```{r}
my_data <- read_csv(here("vignettes/my-data.csv"))
```

And R script files:

```{r}
source(here("vignettes/my-script.R"))
plus_two(my_data$a)
```
